/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTemplateRouteImport } from './routes/_app.template'
import { Route as AppSourcesRouteImport } from './routes/_app.sources'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as ApiPublicUploadClipRouteImport } from './routes/api/public/upload-clip'
import { Route as ApiPublicHooksShotstackRouteImport } from './routes/api/public/hooks/shotstack'
import { Route as ApiPublicCronResolveMomentsRouteImport } from './routes/api/public/cron/resolve-moments'
import { Route as ApiPublicCronPollKickRouteImport } from './routes/api/public/cron/poll-kick'
import { Route as ApiPublicCronExportTrainingRouteImport } from './routes/api/public/cron/export-training'
import { Route as ApiPublicCronChatPulseRouteImport } from './routes/api/public/cron/chat-pulse'
import { Route as ApiPublicCronBackfillRouteImport } from './routes/api/public/cron/backfill'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplateRoute = AppTemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicUploadClipRoute = ApiPublicUploadClipRouteImport.update({
  id: '/api/public/upload-clip',
  path: '/api/public/upload-clip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksShotstackRoute = ApiPublicHooksShotstackRouteImport.update({
  id: '/api/public/hooks/shotstack',
  path: '/api/public/hooks/shotstack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronResolveMomentsRoute =
  ApiPublicCronResolveMomentsRouteImport.update({
    id: '/api/public/cron/resolve-moments',
    path: '/api/public/cron/resolve-moments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPollKickRoute = ApiPublicCronPollKickRouteImport.update({
  id: '/api/public/cron/poll-kick',
  path: '/api/public/cron/poll-kick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronExportTrainingRoute =
  ApiPublicCronExportTrainingRouteImport.update({
    id: '/api/public/cron/export-training',
    path: '/api/public/cron/export-training',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronChatPulseRoute = ApiPublicCronChatPulseRouteImport.update({
  id: '/api/public/cron/chat-pulse',
  path: '/api/public/cron/chat-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronBackfillRoute = ApiPublicCronBackfillRouteImport.update({
  id: '/api/public/cron/backfill',
  path: '/api/public/cron/backfill',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/campaigns': typeof AppCampaignsRoute
  '/library': typeof AppLibraryRoute
  '/pipeline': typeof AppPipelineRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/template': typeof AppTemplateRoute
  '/api/public/upload-clip': typeof ApiPublicUploadClipRoute
  '/api/public/cron/backfill': typeof ApiPublicCronBackfillRoute
  '/api/public/cron/chat-pulse': typeof ApiPublicCronChatPulseRoute
  '/api/public/cron/export-training': typeof ApiPublicCronExportTrainingRoute
  '/api/public/cron/poll-kick': typeof ApiPublicCronPollKickRoute
  '/api/public/cron/resolve-moments': typeof ApiPublicCronResolveMomentsRoute
  '/api/public/hooks/shotstack': typeof ApiPublicHooksShotstackRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/campaigns': typeof AppCampaignsRoute
  '/library': typeof AppLibraryRoute
  '/pipeline': typeof AppPipelineRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/template': typeof AppTemplateRoute
  '/': typeof AppIndexRoute
  '/api/public/upload-clip': typeof ApiPublicUploadClipRoute
  '/api/public/cron/backfill': typeof ApiPublicCronBackfillRoute
  '/api/public/cron/chat-pulse': typeof ApiPublicCronChatPulseRoute
  '/api/public/cron/export-training': typeof ApiPublicCronExportTrainingRoute
  '/api/public/cron/poll-kick': typeof ApiPublicCronPollKickRoute
  '/api/public/cron/resolve-moments': typeof ApiPublicCronResolveMomentsRoute
  '/api/public/hooks/shotstack': typeof ApiPublicHooksShotstackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/template': typeof AppTemplateRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/upload-clip': typeof ApiPublicUploadClipRoute
  '/api/public/cron/backfill': typeof ApiPublicCronBackfillRoute
  '/api/public/cron/chat-pulse': typeof ApiPublicCronChatPulseRoute
  '/api/public/cron/export-training': typeof ApiPublicCronExportTrainingRoute
  '/api/public/cron/poll-kick': typeof ApiPublicCronPollKickRoute
  '/api/public/cron/resolve-moments': typeof ApiPublicCronResolveMomentsRoute
  '/api/public/hooks/shotstack': typeof ApiPublicHooksShotstackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/library'
    | '/pipeline'
    | '/settings'
    | '/sources'
    | '/template'
    | '/api/public/upload-clip'
    | '/api/public/cron/backfill'
    | '/api/public/cron/chat-pulse'
    | '/api/public/cron/export-training'
    | '/api/public/cron/poll-kick'
    | '/api/public/cron/resolve-moments'
    | '/api/public/hooks/shotstack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/campaigns'
    | '/library'
    | '/pipeline'
    | '/settings'
    | '/sources'
    | '/template'
    | '/'
    | '/api/public/upload-clip'
    | '/api/public/cron/backfill'
    | '/api/public/cron/chat-pulse'
    | '/api/public/cron/export-training'
    | '/api/public/cron/poll-kick'
    | '/api/public/cron/resolve-moments'
    | '/api/public/hooks/shotstack'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/campaigns'
    | '/_app/library'
    | '/_app/pipeline'
    | '/_app/settings'
    | '/_app/sources'
    | '/_app/template'
    | '/_app/'
    | '/api/public/upload-clip'
    | '/api/public/cron/backfill'
    | '/api/public/cron/chat-pulse'
    | '/api/public/cron/export-training'
    | '/api/public/cron/poll-kick'
    | '/api/public/cron/resolve-moments'
    | '/api/public/hooks/shotstack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiPublicUploadClipRoute: typeof ApiPublicUploadClipRoute
  ApiPublicCronBackfillRoute: typeof ApiPublicCronBackfillRoute
  ApiPublicCronChatPulseRoute: typeof ApiPublicCronChatPulseRoute
  ApiPublicCronExportTrainingRoute: typeof ApiPublicCronExportTrainingRoute
  ApiPublicCronPollKickRoute: typeof ApiPublicCronPollKickRoute
  ApiPublicCronResolveMomentsRoute: typeof ApiPublicCronResolveMomentsRoute
  ApiPublicHooksShotstackRoute: typeof ApiPublicHooksShotstackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/template': {
      id: '/_app/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof AppTemplateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/upload-clip': {
      id: '/api/public/upload-clip'
      path: '/api/public/upload-clip'
      fullPath: '/api/public/upload-clip'
      preLoaderRoute: typeof ApiPublicUploadClipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shotstack': {
      id: '/api/public/hooks/shotstack'
      path: '/api/public/hooks/shotstack'
      fullPath: '/api/public/hooks/shotstack'
      preLoaderRoute: typeof ApiPublicHooksShotstackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/resolve-moments': {
      id: '/api/public/cron/resolve-moments'
      path: '/api/public/cron/resolve-moments'
      fullPath: '/api/public/cron/resolve-moments'
      preLoaderRoute: typeof ApiPublicCronResolveMomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/poll-kick': {
      id: '/api/public/cron/poll-kick'
      path: '/api/public/cron/poll-kick'
      fullPath: '/api/public/cron/poll-kick'
      preLoaderRoute: typeof ApiPublicCronPollKickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/export-training': {
      id: '/api/public/cron/export-training'
      path: '/api/public/cron/export-training'
      fullPath: '/api/public/cron/export-training'
      preLoaderRoute: typeof ApiPublicCronExportTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/chat-pulse': {
      id: '/api/public/cron/chat-pulse'
      path: '/api/public/cron/chat-pulse'
      fullPath: '/api/public/cron/chat-pulse'
      preLoaderRoute: typeof ApiPublicCronChatPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/backfill': {
      id: '/api/public/cron/backfill'
      path: '/api/public/cron/backfill'
      fullPath: '/api/public/cron/backfill'
      preLoaderRoute: typeof ApiPublicCronBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppTemplateRoute: typeof AppTemplateRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppTemplateRoute: AppTemplateRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiPublicUploadClipRoute: ApiPublicUploadClipRoute,
  ApiPublicCronBackfillRoute: ApiPublicCronBackfillRoute,
  ApiPublicCronChatPulseRoute: ApiPublicCronChatPulseRoute,
  ApiPublicCronExportTrainingRoute: ApiPublicCronExportTrainingRoute,
  ApiPublicCronPollKickRoute: ApiPublicCronPollKickRoute,
  ApiPublicCronResolveMomentsRoute: ApiPublicCronResolveMomentsRoute,
  ApiPublicHooksShotstackRoute: ApiPublicHooksShotstackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
